"""add status to goals

Revision ID: 5d421fca8e87
Revises: 5c67dfe515f5
Create Date: 2026-09-30 18:10:11.106116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d421fca8e87'
down_revision: Union[str, Sequence[str], None] = '5c67dfe515f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###
    # Alembic's autogenerate does not diff CHECK constraints, so this one is
    # written by hand: it is what makes an invalid status impossible even if
    # the API layer is bypassed.
    op.create_check_constraint(
        'ck_goals_status',
        'goals',
        "status IN ('active', 'on_hold', 'completed', 'archived')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_goals_status', 'goals', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'status')
    # ### end Alembic commands ###
